# Generated by Django 6.0.1 on 2026-01-27 14:49

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edibro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=17, region=None, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+234 803 099 9999'. Up to 15 digits is allowed.", regex='^\\+?1?\\d{9, 18}$')]),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
