# Generated by Django 6.0.2 on 2026-02-07 12:04

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxValueValidator(100)])),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxValueValidator(100)])),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=17, region=None, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+234 803 099 9999'. Up to 15 digits is allowed.", regex='^\\+?1?\\d{9, 18}$')])),
                ('website', models.URLField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxValueValidator(50)])),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxValueValidator(300)])),
            ],
        ),
        migrations.CreateModel(
            name='userTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_when', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
